import { Fragment, useState } from "react"
import Head from 'next/head'
import Navbar from '../components/Navbar'
import { TrashIcon, PencilAltIcon } from '@heroicons/react/solid'



export default function Home() {
    const loop = [1, 2, 3, 4, 5, 6, 7, 8]
    const people = [
        { name: 'Wade Cooper' },
        { name: 'Arlene Mccoy' },
        { name: 'Devon Webb' },
        { name: 'Tom Cook' },
        { name: 'Tanya Fox' },
        { name: 'Hellen Schmidt' },
    ]

    const [selected, setSelected] = useState(people[0])

    return (
        <div className="">
            <Head>
                <title>KasirApp | Barang </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />
            <div className="container mx-auto mt-5">
                <h3>Semua Barang</h3>
                <div>

                </div>
                <div className="relative shadow-md sm:rounded-lg mt-4">
                    {/* Table */}
                        <table className="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                            <thead className="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                                <tr className="text-center">
                                    <th scope="col" className="px-6 py-3">
                                        Product name
                                    </th>
                                    <th scope="col" className="px-6 py-3">
                                        Category
                                    </th>
                                    <th scope="col" className="px-6 py-3">
                                        Price
                                    </th>
                                    <th scope="col" className="px-6 py-3">
                                        Aksi
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {loop.map((item, index) => (
                                    <tr className="border-b dark:bg-gray-800 dark:border-gray-700 odd:bg-white even:bg-gray-100 odd:dark:bg-gray-800 even:dark:bg-gray-700 text-center">
                                        <th
                                            scope="row"
                                            className="px-6 py-4 font-medium text-gray-900 dark:text-white whitespace-nowrap"
                                        >
                                            Polpen
                                        </th>
                                        <td className="px-6 py-4">Alat Tulis Kantor</td>
                                        <td className="px-6 py-4">Rp.50.000</td>
                                        <td>
                                            <button class=" bg-red-500 rounded-md px-3 py-2 mr-2"><TrashIcon width={20} /></button>
                                            <button class=" bg-green-500 rounded-md px-3 py-2"><PencilAltIcon width={20} /></button>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                </div>
            </div>

        </div>
    )
}
